=== EspadaV8/squizmatrix/packages/asset.xsd
<?xml version="1.0"?>
<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xsd,v 1.11 2005/06/06 00:39:42 arailean Exp $
*
*/
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="dtype_package">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_type_code">
		<xsd:restriction base="xsd:string">
			<!-- must start with a letter -->
			<xsd:pattern value="[a-zA-Z][a-zA-Z_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_version">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+(\.[0-9]+)+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_name">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_description">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_yes_no">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="yes"/>
			<xsd:enumeration value="no"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_requirement_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="package"/>
			<xsd:enumeration value="asset"/>
			<xsd:enumeration value="system"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dtype_requirement">
		<xsd:sequence>
			<xsd:element name="code"    type="dtype_type_code"/>
			<xsd:element name="version" type="dtype_version"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="dtype_requirement_type" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="dtype_requirements">
		<xsd:sequence>
			<xsd:element name="requirement" type="dtype_requirement" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="dtype_flash_menu_path">
		<xsd:restriction base="xsd:string" minOccurs="0" maxOccurs="1" />
	</xsd:simpleType>

	<xsd:complexType name="dtype_asset_info">
		<xsd:sequence>
			<xsd:element name="package"         type="dtype_package"/>
			<xsd:element name="type_code"       type="dtype_type_code"/>
			<xsd:element name="version"         type="dtype_version"/>
			<xsd:element name="name"            type="dtype_name"/>
			<xsd:element name="description"     type="dtype_description"/>
			<xsd:element name="instantiable"    type="dtype_yes_no"/>
			<xsd:element name="allowed_access"  type="dtype_allowed_access"/>
			<xsd:element name="parent_type"     type="dtype_type_code"/>
			<xsd:element name="requirements"    type="dtype_requirements"/>
			<xsd:element name="flash_menu_path" type="dtype_flash_menu_path"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="asset_info" type="dtype_asset_info" />

</xsd:schema>

=== EspadaV8/squizmatrix/packages/cms/content_type/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>cms</package>
	<type_code>content_type</type_code>
	<version>0.1</version>
	<name>Content Type</name>
	<description>Content Type, base class for editing cell contents</description>
	<instantiable>no</instantiable>
	<system_only>yes</system_only>
	<parent_type>asset</parent_type>
	<requirements>
		<requirement type="asset">
			<code>bodycopy_table</code>
			<version>0.1</version>
		</requirement>
	</requirements>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/system/cron/cron_job/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* Copyright (c) 2003 - Squiz Pty Ltd
*
* $Id: asset.xml,v 1.4 2003/09/26 06:41:21 brobertson Exp $
* $Name: not supported by cvs2svn $
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>cron_job</type_code>
	<version>0.1</version>
	<name>Cron Job</name>
	<description>The Cron Job, a single cron job to be queued and executed by the Cron Manager</description>
	<instantiable>no</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>asset</parent_type>
	<requirements />
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/metadata/metadata_schema/asset.xml
<!--
/**
* Copyright (c) 2003 - Squiz Pty Ltd
*
* $Id: asset.xml,v 1.4 2003/09/26 05:26:26 brobertson Exp $
* $Name: not supported by cvs2svn $
*/
-->

<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../../packages/asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../packages/asset.xsd">
	<package>__core__</package>
	<type_code>metadata_schema</type_code>
	<version>0.1</version>
	<name>Metadata Schema</name>
	<description>Metadata Schema, define a schema for metadata to be attached to assets in the system</description>
	<instantiable>yes</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>folder</parent_type>
	<requirements />
	<flash_menu_path>Schemas</flash_menu_path>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/metadata/metadata_section/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../../packages/asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../packages/asset.xsd">
	<package>__core__</package>
	<type_code>metadata_section</type_code>
	<version>0.1</version>
	<name>Metadata Section</name>
	<description>Metadata Section, group metadata fields into sections</description>
	<instantiable>yes</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>folder</parent_type>
	<requirements />
</asset_info>

=== EspadaV8/squizmatrix/packages/cms/bodycopy/bodycopy/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>cms</package>
	<type_code>bodycopy</type_code>
	<version>0.1</version>
	<name>Bodycopy</name>
	<description>BodyCopy Object, create tables to format content</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>asset</parent_type>
	<requirements>
		<requirement type="system">
			<code>Resolve</code>
			<version>0.1.0</version>
		</requirement>
	</requirements>
</asset_info>

=== EspadaV8/squizmatrix/packages/squiz_suite/suite_manager/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>
<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.2 2010/11/05 04:47:48 csmith Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>squiz_suite</package>
	<type_code>suite_manager</type_code>
	<version>0.1</version>
	<name>Squiz Suite Manager</name>
	<description>Squiz Suite Manager organises connections to Squiz Suite products</description>
	<instantiable>no</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>page</parent_type>
	<requirements>
		<requirement type="system_asset">
			<code>web_folder_web_services</code>
			<version>0.1</version>
		</requirement>
    </requirements>
	<flash_menu_path />
</asset_info>

=== EspadaV8/squizmatrix/core/assets/workflow/workflow_stream/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../../packages/asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.1 2009/11/27 05:39:53 lwright Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../packages/asset.xsd">
	<package>__core__</package>
	<type_code>workflow_stream</type_code>
	<version>0.1</version>
	<name>Workflow Stream</name>
	<description>Defines a possible stream of steps to be taken to approve a workflow. A Workflow Schema may have one or more of these, to define alternate approval paths that those with Admin permission to an applied asset can select when applying for approval.</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>asset</parent_type>
	<requirements />
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/packages/ecommerce/delivery_methods/ecommerce_delivery_method/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../../asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Commercial Module Licence                                |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c) Squiz Pty Ltd (ACN 084 670 600).                     |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file is not open source or freely usable and may be    |
* | used subject to, and only in accordance with, the Squiz Commercial |
* | Module Licence.                                                    |
* | Please refer to http://www.squiz.net/licence for more information. |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.1 2005/07/20 01:17:55 arailean Exp $
*
*/
-->
<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../asset.xsd">
	<package>ecommerce</package>
	<type_code>ecommerce_delivery_method</type_code>
	<version>0.1</version>
	<name>Ecommerce Delivery Method</name>
	<description>Delivery Method Object, the base class for creating delivery methods and processing them</description>
	<instantiable>no</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>asset</parent_type>
	<requirements>
		<requirement type="system">
			<code>System</code>
			<version>3.7.0</version>
		</requirement>
	</requirements>
	<flash_menu_path/>
</asset_info>
