=== EspadaV8/squizmatrix/packages/asset.xsd
<?xml version="1.0"?>
<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xsd,v 1.11 2005/06/06 00:39:42 arailean Exp $
*
*/
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="dtype_package">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_type_code">
		<xsd:restriction base="xsd:string">
			<!-- must start with a letter -->
			<xsd:pattern value="[a-zA-Z][a-zA-Z_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_version">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+(\.[0-9]+)+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_name">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_description">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_yes_no">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="yes"/>
			<xsd:enumeration value="no"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_requirement_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="package"/>
			<xsd:enumeration value="asset"/>
			<xsd:enumeration value="system"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dtype_requirement">
		<xsd:sequence>
			<xsd:element name="code"    type="dtype_type_code"/>
			<xsd:element name="version" type="dtype_version"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="dtype_requirement_type" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="dtype_requirements">
		<xsd:sequence>
			<xsd:element name="requirement" type="dtype_requirement" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="dtype_flash_menu_path">
		<xsd:restriction base="xsd:string" minOccurs="0" maxOccurs="1" />
	</xsd:simpleType>

	<xsd:complexType name="dtype_asset_info">
		<xsd:sequence>
			<xsd:element name="package"         type="dtype_package"/>
			<xsd:element name="type_code"       type="dtype_type_code"/>
			<xsd:element name="version"         type="dtype_version"/>
			<xsd:element name="name"            type="dtype_name"/>
			<xsd:element name="description"     type="dtype_description"/>
			<xsd:element name="instantiable"    type="dtype_yes_no"/>
			<xsd:element name="allowed_access"  type="dtype_allowed_access"/>
			<xsd:element name="parent_type"     type="dtype_type_code"/>
			<xsd:element name="requirements"    type="dtype_requirements"/>
			<xsd:element name="flash_menu_path" type="dtype_flash_menu_path"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="asset_info" type="dtype_asset_info" />

</xsd:schema>

=== EspadaV8/squizmatrix/packages/ipb/ipb_post/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This MySource Matrix CMS file is Copyright (c) Squiz Pty Ltd       |
* | ACN 084 670 600                                                    |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | IMPORTANT: Your use of this Software is subject to the terms of    |
* | the Licence provided in the file licence.txt. If you cannot find   |
* | this file please contact Squiz (www.squiz.net) so we may provide   |
* | you a copy.                                                        |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.3 2010/05/05 07:13:23 ewang Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>ipb</package>
	<type_code>ipb_post</type_code>
	<version>0.1</version>
	<name>IPB Post</name>
	<description>An asset to represent a topic in Invision Power Board</description>
	<instantiable>no</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>ipb_topic</parent_type>
	<requirements />
	<flash_menu_path>IPB</flash_menu_path>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/designs/design_areas/design_area_colourise_image/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>design_area_colourise_image</type_code>
	<version>0.1</version>
	<name>Colourise Image Design Area</name>
	<description>This design area allows you to let the system user colourise images</description>
	<instantiable>yes</instantiable>
	<system_only>yes</system_only>
	<parent_type>design_area</parent_type>
	<requirements>
		<requirement type="asset">
			<code>design_area</code>
			<version>0.1</version>
		</requirement>
	</requirements>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/designs/design_areas/menu/design_area_menu_recursive/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>design_area_menu_recursive</type_code>
	<version>0.1</version>
	<name>Recursive Menu Design Area</name>
	<description>Menuing design area used to allow the recursivly generate menus</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>design_area_menu_type</parent_type>
	<requirements>
		<requirement type="asset">
			<code>design_area_menu_type</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/designs/design_areas/menu/design_area_menu_page_lineage/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>design_area_menu_page_lineage</type_code>
	<version>0.1</version>
	<name>Page Lineage Menu Design Area</name>
	<description>Menuing design area used to display the current lineage (path from site root to the current page). Also called crumming</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>design_area_menu_type</parent_type>
	<requirements>
		<requirement type="asset">
			<code>design_area_menu_type</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/packages/cms/cron_jobs/cron_job_manage_pending_accounts/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.1 2006/04/27 03:19:36 lwright Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>cms</package>
	<type_code>cron_job_manage_pending_accounts</type_code>
	<version>0.2</version>
	<name>Manage Pending Accounts Cron Job</name>
	<description>Manages pending accounts created by account managers. This cron job handles the resending of validation emails to, or deletion of pending accounts that remain pending for an extended period of time.</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>cron_job</parent_type>
	<requirements />
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/users/backend_user/asset.xml
<!--
/**
* Copyright (c) 2003 - Squiz Pty Ltd
*
* $Id: asset.xml,v 1.4 2003/09/26 05:26:29 brobertson Exp $
* $Name: not supported by cvs2svn $
*/
-->

<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>backend_user</type_code>
	<version>0.1</version>
	<name>Backend User</name>
	<description>Backend Users are the only users that have access to the backend</description>
	<instantiable>yes</instantiable>
	<allowed_access>system_user</allowed_access>
	<parent_type>user</parent_type>
	<requirements>
		<requirement type="asset">
			<code>user</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path>Users</flash_menu_path>
</asset_info>

=== EspadaV8/squizmatrix/core/assets/designs/design_areas/design_area_constant_button/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* Copyright (c) 2003 - Squiz Pty Ltd
*
* $Id: asset.xml,v 1.5 2003/11/12 18:02:27 brobertson Exp $
* $Name: not supported by cvs2svn $
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>__core__</package>
	<type_code>design_area_constant_button</type_code>
	<version>0.2</version>
	<name>Constant Button Design Area</name>
	<description>This design area allows constant links to be made in the design</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>design_area</parent_type>
	<requirements>
		<requirement type="asset">
			<code>design_area</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path/>
</asset_info>

=== EspadaV8/squizmatrix/packages/redis_non_atomic/cache_storage_redis_non_atomic/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.1 2013/01/22 05:03:07 ewang Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>redis_non_atomic</package>
	<type_code>cache_storage_redis_non_atomic</type_code>
	<version>0.1</version>
	<name>Non-atomic Redis Cache Storage</name>
	<description>Storage mechanism for content cache data using non-atomic redis operations</description>
	<instantiable>no</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>cache_storage_redis</parent_type>
   <requirements>
      <requirement type="asset">
         <code>cache_storage_redis</code>
         <version>0.1</version>
      </requirement>
   </requirements>
   <flash_menu_path />
</asset_info>
