=== EspadaV8/squizmatrix/packages/asset.xsd
<?xml version="1.0"?>
<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xsd,v 1.11 2005/06/06 00:39:42 arailean Exp $
*
*/
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="dtype_package">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_type_code">
		<xsd:restriction base="xsd:string">
			<!-- must start with a letter -->
			<xsd:pattern value="[a-zA-Z][a-zA-Z_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_version">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+(\.[0-9]+)+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_name">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_description">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="dtype_yes_no">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="yes"/>
			<xsd:enumeration value="no"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dtype_requirement_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="package"/>
			<xsd:enumeration value="asset"/>
			<xsd:enumeration value="system"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dtype_requirement">
		<xsd:sequence>
			<xsd:element name="code"    type="dtype_type_code"/>
			<xsd:element name="version" type="dtype_version"/>
		</xsd:sequence>
		<xsd:attribute name="type" type="dtype_requirement_type" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="dtype_requirements">
		<xsd:sequence>
			<xsd:element name="requirement" type="dtype_requirement" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="dtype_flash_menu_path">
		<xsd:restriction base="xsd:string" minOccurs="0" maxOccurs="1" />
	</xsd:simpleType>

	<xsd:complexType name="dtype_asset_info">
		<xsd:sequence>
			<xsd:element name="package"         type="dtype_package"/>
			<xsd:element name="type_code"       type="dtype_type_code"/>
			<xsd:element name="version"         type="dtype_version"/>
			<xsd:element name="name"            type="dtype_name"/>
			<xsd:element name="description"     type="dtype_description"/>
			<xsd:element name="instantiable"    type="dtype_yes_no"/>
			<xsd:element name="allowed_access"  type="dtype_allowed_access"/>
			<xsd:element name="parent_type"     type="dtype_type_code"/>
			<xsd:element name="requirements"    type="dtype_requirements"/>
			<xsd:element name="flash_menu_path" type="dtype_flash_menu_path"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="asset_info" type="dtype_asset_info" />

</xsd:schema>

=== EspadaV8/squizmatrix/packages/search/searchbox/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>
<!--
/**
* Copyright (c) 2003 - Squiz Pty Ltd
*
* $Id: asset.xml,v 1.1.1.1 2003/10/08 01:20:58 dwong Exp $
* $Name: not supported by cvs2svn $
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>search</package>
	<type_code>design_area_searchbox</type_code>
	<version>0.1</version>
	<name>Searchbox design area</name>
	<description>Input textbox to be used in designs for searching.</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>design_area</parent_type>
	<requirements>
		<requirement type="asset">
			<code>design_area</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path />
</asset_info>

=== EspadaV8/squizmatrix/packages/cms/page_templates/page_multiple_page_page/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Commercial Module Licence                                |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c) Squiz Pty Ltd (ACN 084 670 600).                     |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file is not open source or freely usable and may be    |
* | used subject to, and only in accordance with, the Squiz Commercial |
* | Module Licence.                                                    |
* | Please refer to http://www.squiz.net/licence for more information. |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.2 2005/11/21 04:34:05 dmckee Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>cms</package>
	<type_code>page_multiple_page_page</type_code>
	<version>0.1</version>
	<name>Multiple Page Page</name>
	<description>Multiple Page Page, Is a part of the Multiple Page</description>
	<instantiable>no</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>bodycopy</parent_type>
	<requirements>
		<requirement type="asset">
			<code>page</code>
			<version>0.2</version>
		</requirement>
		<requirement type="asset">
			<code>bodycopy</code>
			<version>0.1</version>
		</requirement>
		<requirement type="asset">
			<code>page_multiple_page</code>
			<version>0.1</version>
		</requirement>
	</requirements>
	<flash_menu_path>Pages</flash_menu_path>
</asset_info>

=== EspadaV8/squizmatrix/packages/bulkmail/bulkmail_post_office_default/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../../packages/asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Commercial Module Licence                                |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c) Squiz Pty Ltd (ACN 084 670 600).                     |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file is not open source or freely usable and may be    |
* | used subject to, and only in accordance with, the Squiz Commercial |
* | Module Licence.                                                    |
* | Please refer to http://www.squiz.net/licence for more information. |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.1 2005/11/01 22:13:13 rong Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../packages/asset.xsd">
	<package>bulkmail</package>
	<type_code>bulkmail_post_office_default</type_code>
	<version>0.1</version>
	<name>Default Bulkmail Post Office</name>
	<description>The Default Bulkmail Post Office system asset.</description>
	<instantiable>yes</instantiable>
	<allowed_access>system</allowed_access>
	<parent_type>bulkmail_post_office</parent_type>
	<requirements>
		<requirement type="asset">
			<code>bulkmail_manager</code>
			<version>0.1</version>
		</requirement>
	</requirements>
</asset_info>

=== EspadaV8/squizmatrix/packages/calendar/page_templates/page_calendar_rolling/asset.xml
<?xml version='1.0' encoding='UTF-8' ?>
<?xml-stylesheet href="../../asset.xsl" type="text/xsl"?>

<!--
/**
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Squiz.net Open Source Licence                                      |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | Copyright (c), 2003 Squiz Pty Ltd (ABN 77 084 670 600).            |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
* | This source file may be used subject to, and only in accordance    |
* | with, the Squiz Open Source Licence Agreement found at             |
* | http://www.squiz.net/licence.                                      |
* | Make sure you have read and accept the terms of that licence,      |
* | including its limitations of liability and disclaimers, before     |
* | using this software in any way. Your use of this software is       |
* | deemed to constitute agreement to be bound by that licence. If you |
* | modify, adapt or enhance this software, you agree to assign your   |
* | intellectual property rights in the modification, adaptation and   |
* | enhancement to Squiz Pty Ltd for use and distribution under that   |
* | licence.                                                           |
* +- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
*
* $Id: asset.xml,v 1.2 2006/02/15 01:06:48 rhoward Exp $
*
*/
-->

<asset_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../asset.xsd">
	<package>calendar</package>
	<type_code>page_calendar_rolling</type_code>
	<version>0.2</version>
	<name>Rolling Calendar Page</name>
	<description>Rolling Calendar Page, displays events for a specified interval relative to the current day</description>
	<instantiable>yes</instantiable>
	<allowed_access>backend_user</allowed_access>
	<parent_type>page</parent_type>
	<requirements>
		<requirement type="asset">
			<code>page</code>
			<version>0.2</version>
		</requirement>
	</requirements>
	<flash_menu_path>Calendar</flash_menu_path>
</asset_info>
